# global configs
scan_timeout = 100
command_timeout = 1000

[username]
show_always = true
format = '[$user]($style)@'

[shell]
disabled = false
powershell_indicator = 'ó°¨Š'
bash_indicator = 'î¯Š'
cmd_indicator = 'î¯„'
style = 'white bold'

[hostname]
ssh_only = false
ssh_symbol = ' ğŸŒ'
format = '[$hostname$ssh_symbol]($style) in '

[shlvl]
disabled = false
threshold = 1

[os]
disabled = false

[os.symbols]
Arch = "ó°£‡ "
Ubuntu = "ó°•ˆ "
Windows = "ó°–³ "
